version: '3.3'

services: 
    app:
      build: .
      volumes: 
        - .:/app
      working_dir: /app
      ports: 
        - 3000:3000
      depends_on:
        - db
      networks: 
        - back
      command: ['npm', 'run', 'dev']
    db:
      image: nouchka/sqlite3
      stdin_open: true
      tty: true
      volumes:
        - ./db/:/root/db/
      ports: 
        - 3001:3001
      networks: 
        - back
networks:
  back:
    driver: bridge